### ISSUE TITLE
Rename Parsers

### ISSUE THREAD

**Issue by organisciak** [massivetexts/htrc-feature-reader#10]
Two issues brought up in https://github.com/htrc/htrc-feature-reader/issues/32:

- [ ] jsonVolumeParser is camelCase, where the convention is CapCase. Easy fix.
- [ ] Is 'FileHandler' more appropriate than `Parser`?

**Comment by bmschmidt** [comment]
In my fork, I've refactored this to use `JsonFileHandler`, `ParquetFileHandler`, etc. Sound good?
