### ISSUE TITLE
Remove legacy 2.7 code

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/htrc-feature-reader#16]
Support for python 2.7 ended on January 1, 2020.

[scikit, numpy, pandas](https://python3statement.org/), etc. have all stopped 2.7 support.

Given that the old releases of this library will continue to provide good performance for 2.7, should the new version be released for python3 only?

(Asking because I don't want to write dual-use code).

**Comment by organisciak** [comment]
Yes, I _very_ subtly did this here: https://github.com/massivetexts/htrc-feature-reader/commit/c1cbb0c6fb6c0047501b0857a8574afadc2aa7bd

I'll always remember where I was on October 8th: https://twitter.com/POrg/status/1181616750799900672

**Comment by organisciak** [comment]
After removing it from tests and setup.py (29b46f0ee1879), anything else? We could gradually remove cross-compatible code, but I wouldn't worry now. I think the last thing is to remove 2.7 from build targets.

**Comment by bmschmidt** [comment]
Oh good! Yeah, I think just kill the cross-compatible code when encountered.

The last thing I would do if I were you is permanently tagging one release as the last 2.7-compatible one on github, too, and maybe linking to it from the readme for a couple years.

So the goal is 3.7, specifically, not 3.5?

**Comment by bmschmidt** [comment]
Changing the pull request name to reflect that at some point, someone should go through and pull out all of the special-case handling, the imports of six and __future__, etc.

But I don't think either of us should be spending time on this right now.

**Comment by organisciak** [comment]
No, the goal is 3.5 and up, which should also be compatible with 3.6 and 3.7. I'm not against gradually moving that up and dropping explicit support for older minor releases. I don't even know what changes between them, i.e. I don't remember why 3.5 and not, say, 3.4.

**Comment by bmschmidt** [comment]
I was asking just because of the chunk in tests. But thinking a bit more, can I propose 3.6? I am a big fan of the f-strings introduced in 3.6, and have been using them a bit.

I have not been using `Path()` and `os.pathlike,` which are better in 3.6, but if we go much farther down the pairtree route, it may be useful.

release dates arent' *so* different 3.5 vs 3.6:

```
Python 3.2 - 20 Feb 2011 - ... - What's new
Python 3.3 - 29 Sep 2012 - ... - What's new
Python 3.4 - 16 Mar 2014 - ... - What's new
Python 3.5 - 13 Sep 2015 - release notes - What's new
Python 3.6 - 23 Dec 2016 - release notes - What's new
Python 3.7 - 27 Jun 2018
Python 3.8 - 14 Oct 2019
```

**Comment by bmschmidt** [comment]
I've got new issues on both sides of this.

## Pro-3.5 

1. Ubuntu 16.04 (which I still have on my laptop) is on python 3.5. 18.04 is the newest LTS, but there's some reason to support 16.04 out-of-the-box.

## Pro-3.6

1. ZipFile supports an 'open' protocol that greatly simplifies FileHandler methods on zip objects.

**Comment by bmschmidt** [comment]
Change of mind again. I propose supporting 3.5 and above.

But *writing to* (not reading from) my weird zipfile format will require 3.6. All other methods should be 3.5-compatible.

**Comment by organisciak** [comment]
I'm fine with 3.6 instead of 3.5. We don't need to hunt down legacy code to intentionally distance it from 2.7.
