### ISSUE TITLE
Batched zipfiles as storage backend

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/htrc-feature-reader#17]
OK, here's the last insane feature request I'll file this week, I promise. But it's been at the back of my head the whole time. Here's the problem: to work with these in NYU's HPC environment, I need an id-based storage backend that isn't pairtree, because I can't have millions of inodes to myself on their filesystem. But I'd like it to play alongside other forms of access.

I was just gonna roll it for myself, but David Mimno's comment about storing Hathi as 1000-file .tar archives made me try to spec out this format because maybe it isn't crazy. It bundles multiple json files into an archive (not 25,000,000 inodes), but which also allows fast random access.

# Storing all of Hathi in zipfiles.

I'm calling this format ziptree. As a whole Hathi format, it is 4096 zipfiles, each with about 4,000 files in it. (More--like, 12,000--if you try to dump parquet files in there too.) I was going to use a key-value store, but this really is about files at heart; and there's no key-value database as widespread as the zip format.

## Placing books in zipfiles with hashes.

The home for each Hathi book is determined by the sha1 hash of the id. So if the hash of the id is `64a1569492...`, the zip location is `files/64a.zip`. This makes it easy to retrieve any file. It also ensures that zipfile sizes are evenly balanced.

# FAQ (I imagine)

Q: Why recompress for zip? Isn't that costly?
A: Zip can store files without any compression, and that's what we're doing here.

Q: Is it slow to fill the zipfiles?
A: I find it stunningly fast to write from pairtree to 4,000 zipfiles on SSD: I can do a few hundred a second. Nearly I/O limited, it seems, even when we swap to a different zipfile for each write request.

Q: Is the query time slower than filesystem-based methods?
A: That's the question. I don't know. Maybe it's faster, because you don't have to access half a dozen different directory inodes for every read. But it seems fine. On SSD--which isn't where this is likely to happen, but still--I can get about 1 millisecond per request to pull the bytes of the file into memory when there are 10,000 files in the structure.

Q: Is this a good idea if the zipfiles are being continuously synced to your dropbox?
A: No, it is not. 

# Storage of fewer than 15,000,000 files.

This isn't really a tree, but I was thinking it could be because there's an interesting generalizable strategy here.

1. For fewer than 1K files, store using the filesystem directory.
2. For 1K to 64K files, store in 16 zip files of up to 4K entries each.
3. For 64K to 1024K files, store in 256 zip files of up to 4K each.
4. 1M to 16M files, store in 4,096 different zipfiles. Maybe they should be in 16 folders or something.

It would not be overwhelmingly expensive, from what I've seen, to switch from one of these formats to another on the fly.

**Comment by bmschmidt** [comment]
OK, I've got this working along with a lot of the refactor. Not crazy fast, but it'll work.

**Comment by organisciak** [comment]
Separate from the giant merge request (or once it's merged), could you write a test for this to demonstrate use, including example files in `tests`?

**Comment by bmschmidt** [comment]
Yes. Assigning myself in the task list to reflect why the issue is still open.

**Comment by bmschmidt** [comment]
Example in examples, although it could be more exhaustively documented later. Test in tests, although it's the same test we're using for everything.
