### ISSUE TITLE
Pass unindexed frames, internally and to users?

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/htrc-feature-reader#20]
This is very much a question, because I have simply never understood how to make effective use of pandas indexes. But in my code additions--and also in @organisciak's--I see a lot of calls to `reset_index()` before necessary operations can happen, and then the setting of indexes at the end.

The code in the new chunked_tokenlist implementation is even slightly broken because I don't understand how to properly set a multilevel index.

While the indexes can be useful if users are accessing the data in a particular order (pages, then sections, etc.) they seem counterproductive if you want to work in a different direction. For plenty of operations that I do, the first step on the output of 'tokenlist()' is to destroy the index so that 'groupby' works transparently.

Maybe I'm just using these wrong. But I suspect many operations could be sped up if the core frames were passed among functions without indexes, and then indexes were added before sending them to users in the final step. It also allows, discussed in #8, for smaller files on disk in parquet.

I set up a quick branch to test what happens if we optionally remove indexes internally. It looks like a substantial amount of time is being spent on index creation and destruction; if we use unindexed frames, things happen maybe ~25% faster. Not counting the time that's lost destroying the indexes for the next step.

![image](https://user-images.githubusercontent.com/1110758/73140519-aac34100-4047-11ea-84e6-96571d615b8b.png)

**Comment by organisciak** [comment]
This might be a good future consideration, given how the strides that Pandas has made in columnar retrieval performance. It would require some thought around refactoring the internal code, retraining users, and possible use cases. For now, the potential difference is too small given the development and training cost as well as the tax on reverting long-time decisions, but I'll keep an eye on avoiding unnecessary index changes (or premature index setting if it is expected to change). On the user end, the index matches the natural structure of the data as well as aligning with the type of subsets that one might want.

![image](https://user-images.githubusercontent.com/58351/73154224-df5cea00-4093-11ea-928e-d54912d315b2.png)
