### ISSUE TITLE
Reduce unnecessary kwargs use

### ISSUE THREAD

**Issue by organisciak** [massivetexts/htrc-feature-reader#22]
There are a couple of functions that try to pull a keyword argument out of kwargs when they're using it directly rather than passing it on. This makes documentation tricky and debugging trickier, and the code needs to be reviewed to ensure we only use kwargs when necessary.

**Comment by bmschmidt** [comment]
Valid complaint, sorry about this. The primary reason rationale for these was to make a distinction between `None` as a valid argument, and `None` as a placeholder for no passed value for the compression methods in particular. I switched to 'default' for the latter case, but when this happens we should make sure

1. That there's not some weird default-handling going on
2. That the argument is inserted into further calls down the line.

**Comment by organisciak** [comment]
'default' is fine, I like what you did. We could also use the string `'none'`, though when unsure I hew to Pandas convention, where they use `None`.

The tests **REALLY** helped me in point 2.

There are a number of useful places for kwargs in the new code, because different classes can be swapped and sometimes certain classes need more args than others, most of what I did here was change the expected args to be explicit.
