### ISSUE TITLE
Summary of some syntax changes on new features.

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/htrc-feature-reader#27]
A couple notes on https://github.com/massivetexts/htrc-feature-reader/pulls for @organisciak's review.

1. The `Volume` method `save_parquet` has been renamed to `save`, with a default format of parquet. 
(It would be reasonable to gather a file from the web using an http resolver, and then save with format json.)
2. When using `save(format='parquet')`, I've added a new set of options passed to `ParquetFileHandler.write`. Instead of four separate args indicating files, I've switched it to
one that just uses a `files` argument like ['tokens', 'meta'] to determine what to write. This makes passing things around simpler, and simplifies documentation by grouping like things together. Maybe it's bad, though.
3. chunked_tokenlist has been renamed `_chunked_tokenlist`, and the args to `tokenlist` now include all descriptions of chunking, too. As an architecture issue, this works better; as a documentation one, it probably has  a couple issues.
4. I added a warning to FeatureReader when called with a single item. Probably this should be reverted, because it only really nags. But I figure why not steer towards Volume?

I've extended further the Accessing by IDs notebook, to include a discussion of how you can build an infinitely extensible fallback chain. https://github.com/massivetexts/htrc-feature-reader/blob/caching/examples/Accessing%20volumes%20by%20ids.ipynb 

```python

import yaml
s = """
-
  id_resolver: local
  dir: /tmp/loc
  format: parquet
  compression: gzip
  token_kwargs:
    drop_section: true
    sections: body
    pos: false
-
  id_resolver: pairtree
  dir: /drobo/feature-counts
  format: json
  compression: bz2
  cache: false
-
  format: json
  compression: null
  id_resolver: "http"
"""

config = yaml.load(s, yaml.SafeLoader)
p = Path(config[0]['dir'])
if p.exists():
    shutil.rmtree(p)
p.mkdir()

def resolver_factory(id_resolver, **kwargs):
    return htrc_features.resolvers.resolver_nicknames[id_resolver](**kwargs)

def combine_resolvers(l):
    assert(len(l) >= 2)
    first = l[0]
    rest = l[1:]
    if len(rest) > 1:
        second_choice = combine_resolvers(rest)
    else:
        second_choice = resolver_factory(**rest[0])
    with_fallback = caching.make_fallback_resolver(first['id_resolver'], second_choice, cache = first.get("cache", True))
    del first['id_resolver']
    return with_fallback(**first)



bens_resolver = combine_resolvers(config)
Volume(id="mdp.39015012434786", id_resolver = bens_resolver).tokenlist(pos=False, section="default")

```

**Comment by organisciak** [comment]
2. I prefer the original approach as a general philosophy, since it's more apparent in the args rather than relying on the documentation, but the change follows naturally from changing `save_parquet` to `save`.
3. That's fine. We'll tinker with documentation as we go along.
4. Nudging users toward certain practices is appropriate for this type of library.
